[package]
name = "img-convert"
version = "1.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
image = {version = "0.25.5", features = ["avif"]}
nasm-rs = "0.3.0"
ravif = "0.11.11"
rgb = "0.8.50"
webp = "0.3.0"
